;
; See WindowPadX.html for more details about configuring WindowPadX.
;

[Options]
TitleMatchMode=2

RecenterMouse=1
; when the window is moved
RecenterOnlyIfOutside=1
; recenter only if the mouse is outside the window new position

;
; [Hotkeys]: Hotkeys which are active by default.
;   Hotkey sets using standard modifier keys such as
;     * Ctrl (^)
;     * Win (#)
;     * Alt (!)
;     * Shift (+)
;     * For more see: http://l.autohotkey.net/docs/Hotkeys.htm
;   should be placed directly in this section. [Hotkeys: NAME] sections
;   must be enabled/disabled by a hotkey defined in this section.
;
[Hotkeys]
; Win+Numpad for Active Window:
#Numpad1 = WPXA_Move, -1, +1,  0.5, 0.5
#Numpad2 = WPXA_Move,  0, +1,  1.0, 0.5
#Numpad3 = WPXA_Move, +1, +1,  0.5, 0.5
#Numpad4 = WPXA_Move, -1,  0,  0.5, 1.0
#Numpad5 = WPXA_Move,  0,  0,  0.5, 1.0
#Numpad6 = WPXA_Move, +1,  0,  0.5, 1.0
#Numpad7 = WPXA_Move, -1, -1,  0.5, 0.5
#Numpad8 = WPXA_Move,  0, -1,  1.0, 0.5
#Numpad9 = WPXA_Move, +1, -1,  0.5, 0.5
#!Numpad1 = WPXA_MoveMouseToMonitor, 1
#!Numpad2 = WPXA_MoveMouseToMonitor, 2
#!Numpad5 = WPXA_ClipCursorToCurrentMonitorToggle
#!Numpad0 = WPXA_MouseLocator
~RButton & LButton = WPXA_MouseLocator

#NumpadAdd = WPXA_MaximizeToggle
#NumpadEnter = WPXA_MoveWindowToMonitor, Next
#NumpadDiv = WPXA_MinimizeWindowsOnMonitor, 1
#!NumpadDiv = WPXA_GatherWindowsOnMonitor, 1
#NumpadMult = WPXA_MinimizeWindowsOnMonitor, 2
#!NumpadMult = WPXA_GatherWindowsOnMonitor, 2
#NumpadSub = WPXA_TopToggle


; Custom modifier keys:
CapsLock = Hotkeys, Active Window (WADS)
Numpad0 = Hotkeys, Active Window (Numpad)
NumpadSub = Hotkeys, Previous Window (Numpad)

;
; [Hotkeys: xxx]: Hotkeys which are enabled/disabled via the Hotkeys command.
;                 These are typically used to implement custom modifier keys.
;
[Hotkeys: Active Window (WADS)]
;Always On Top for active window
Tab = WPXA_TopToggle

;Transparancy on/off for active window
Space = WPXA_TransparentToggle

;Locks the mouse to active monitor (not allowed to leave the boarders)
; WARNING: Currently there is a bug so that it is not possible to switch it off again (or access start menu)
` = WPXA_ClipCursorToCurrentMonitorToggle

;Move mouse to center of monitor number
1 = WPXA_MoveMouseToMonitor, 1
2 = WPXA_MoveMouseToMonitor, 2
3 = WPXA_MoveMouseToMonitor, 3

;Move active window to monitor number
q = WPXA_MoveWindowToMonitor, 1
w = WPXA_MoveWindowToMonitor, 2
e = WPXA_MoveWindowToMonitor, 3

;Move previous window to monitor number
a = WPXA_MoveWindowToMonitor, 1, p
s = WPXA_MoveWindowToMonitor, 2, p
d = WPXA_MoveWindowToMonitor, 3, p

;Send ALL windows to monitor number
z = WPXA_GatherWindowsOnMonitor, 1
x = WPXA_GatherWindowsOnMonitor, 2
c = WPXA_GatherWindowsOnMonitor, 3

;Basic window placement alternative 30 : 70 plassering
Left = WPXA_Move, -1,  0,  0.3, 1.0
Right = WPXA_Move, +1,  0,  0.7, 1.0
Up = WPXA_MaximizeToggle
Down = WPXA_Move, -0.4, 0,  0.5, 1


;####################################################################
;####           Window Placement on current monitor             #####
;####################################################################
;Command, HorizontalOffset, VerticalOffset, PercentageWidth, PercentageHeight
;??Note that offsets are for center of window??

;Place active window on edge L30-L50-R50-R70 (CapsLock) - Click twice to halve a windows size.
;Command, HorizontalOffset, VerticalOffset, PercentageWidth, PercentageHeight
v = WPXA_Move, -1, +1,  0.3, 0.5
b = WPXA_Move, -1, +1,  0.5, 0.5
n = WPXA_Move, +1, +1,  0.5, 0.5
m = WPXA_Move, +1, +1,  0.7, 0.5

f = WPXA_Move, -1,  0,  0.3, 1.0
g = WPXA_Move, -1,  0,  0.5, 1.0
h = WPXA_Move, +1,  0,  0.5, 1.0
j = WPXA_Move, +1,  0,  0.7, 1.0

r = WPXA_Move, -1, -1,  0.3, 0.5
t = WPXA_Move, -1, -1,  0.5, 0.5
y = WPXA_Move, +1, -1,  0.5, 0.5
u = WPXA_Move, +1, -1,  0.7, 0.5

;Place active window in inner positions LI15-LI25-RI25-RI-35 (CapsLock + Alt)
;Intented to be used in combination with doubletap for normal window placement.
!v = WPXA_Move, -0.647, +1,  0.15, 0.5
!b = WPXA_Move, -0.333, +1,  0.25, 0.5
!n = WPXA_Move, +0.333, +1,  0.25, 0.5
!m = WPXA_Move, -0.077, +1,  0.35, 0.5

!f = WPXA_Move, -0.647,  0,  0.15, 1.0
!g = WPXA_Move, -0.333,  0,  0.25, 1.0
!h = WPXA_Move, +0.333,  0,  0.25, 1.0
!j = WPXA_Move, -0.077,  0,  0.35, 1.0

!r = WPXA_Move, -0.647, -1,  0.15, 0.5
!t = WPXA_Move, -0.333, -1,  0.25, 0.5
!y = WPXA_Move, +0.333, -1,  0.25, 0.5
!u = WPXA_Move, -0.077, -1,  0.35, 0.5

[Hotkeys: Active Window (Numpad)]
;MODIFIER:  Numpad 0
;Tredje kolonne: Breddeandel,   Fjerde kolonne:  Høyde andel
*Numpad1 = WPXA_Move, -1, +1,  0.5, 0.5
*Numpad2 = WPXA_Move,  0, +1,  1.0, 0.5
*Numpad3 = WPXA_Move, +1, +1,  0.5, 0.5
*Numpad4 = WPXA_Move, -1,  0,  0.5, 1.0
*Numpad5 = WPXA_Move,  0,  0,  0.5, 1.0
*Numpad6 = WPXA_Move, +1,  0,  0.5, 1.0
*Numpad7 = WPXA_Move, -1, -1,  0.5, 0.5
*Numpad8 = WPXA_Move,  0, -1,  1.0, 0.5
*Numpad9 = WPXA_Move, +1, -1,  0.5, 0.5
*NumpadAdd = WPXA_MaximizeToggle
*NumpadEnter = WPXA_MoveWindowToMonitor, Next

;Always On Top or Transparancy for active window
*NumpadDiv = WPXA_TopToggle
*NumpadMult = WPXA_TransparentToggle


[Hotkeys: Previous Window (Numpad)]
;MODIFIER:  Numpad -
;Tredje kolonne: Breddeandel,   Fjerde kolonne:  Høyde andel
*Numpad1 = WPXA_Move, -1, +1,  0.5, 0.5,  P
*Numpad2 = WPXA_Move,  0, +1,  1.0, 0.5,  P
*Numpad3 = WPXA_Move, +1, +1,  0.5, 0.5,  P
*Numpad4 = WPXA_Move, -1,  0,  0.5, 1.0,  P
*Numpad5 = WPXA_Move,  0,  0,  0.5, 1.0,  P
*Numpad6 = WPXA_Move, +1,  0,  0.5, 1.0,  p
*Numpad7 = WPXA_Move, -1, -1,  0.5, 0.5,  p
*Numpad8 = WPXA_Move,  0, -1,  1.0, 0.5,  p
*Numpad9 = WPXA_Move, +1, -1,  0.5, 0.5,  p
*NumpadAdd = WPXA_MaximizeToggle,  p
*NumpadEnter = WPXA_MoveWindowToMonitor, Next,  p

;Always On Top or Transparancy for active window
*NumpadDiv = WPXA_TopToggle,  p
*NumpadMult = WPXA_TransparentToggle,  p

;
; [Exclude Windows]: Hotkeys are disabled for these windows.
;
[Exclude Windows]
Window=Virtual PC
Window=Remote Desktop

;
; [Gather: Exclude Windows]: WPXA_GatherWindowsOnMonitor ignores these windows when gathering.
;
[Gather: Exclude Windows]
Window=ahk_class SideBar_AppBarWindow
Window=ahk_class SideBar_HTMLHostWindow
Window=ahk_class BasicWindow

;
; [Gather: Exclude Processes]: WPXA_GatherWindowsOnMonitor ignores windows belonging to these processes.
;                              It is usually not necessary to use both this and the above.
;
[Gather: Exclude Processes]
; Process=sidebar.exe
Process=clocx.exe
